# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(588, 371)
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setGeometry(QtCore.QRect(120, 80, 351, 191))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_email = QtWidgets.QLabel(self.widget)
        self.lbl_email.setObjectName("lbl_email")
        self.gridLayout.addWidget(self.lbl_email, 0, 0, 1, 1)
        self.ln_email = QtWidgets.QLineEdit(self.widget)
        self.ln_email.setObjectName("ln_email")
        self.gridLayout.addWidget(self.ln_email, 0, 1, 1, 2)
        self.lbl_password = QtWidgets.QLabel(self.widget)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout.addWidget(self.lbl_password, 1, 0, 1, 1)
        self.ln_password = QtWidgets.QLineEdit(self.widget)
        self.ln_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ln_password.setObjectName("ln_password")
        self.gridLayout.addWidget(self.ln_password, 1, 1, 1, 2)
        self.btn_login = QtWidgets.QPushButton(self.widget)
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 2, 1, 1, 1)
        self.cmb_dept = QtWidgets.QComboBox(self.widget)
        self.cmb_dept.setObjectName("cmb_dept")
        self.cmb_dept.addItem("")
        self.cmb_dept.addItem("")
        self.cmb_dept.addItem("")
        self.gridLayout.addWidget(self.cmb_dept, 2, 2, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.lbl_email.setText(_translate("Login", "Email"))
        self.lbl_password.setText(_translate("Login", "Password"))
        self.btn_login.setText(_translate("Login", "Login"))
        self.cmb_dept.setItemText(0, _translate("Login", "HR Dept. Manager"))
        self.cmb_dept.setItemText(1, _translate("Login", "General Manager"))
        self.cmb_dept.setItemText(2, _translate("Login", "Finance Dept. Manager"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
