# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prims.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(673, 827)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 360, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cmbPositionPrimPage = QtWidgets.QComboBox(Dialog)
        self.cmbPositionPrimPage.setGeometry(QtCore.QRect(70, 410, 241, 31))
        self.cmbPositionPrimPage.setObjectName("cmbPositionPrimPage")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(390, 360, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lnIdPrimPage = QtWidgets.QLineEdit(Dialog)
        self.lnIdPrimPage.setGeometry(QtCore.QRect(390, 410, 241, 31))
        self.lnIdPrimPage.setObjectName("lnIdPrimPage")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(220, 10, 241, 261))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../PycharmProjects/pythonProject/images/version2.0.png"))
        self.label_3.setObjectName("label_3")
        self.btnAdjustPositionPrimPage = QtWidgets.QPushButton(Dialog)
        self.btnAdjustPositionPrimPage.setGeometry(QtCore.QRect(70, 460, 241, 31))
        self.btnAdjustPositionPrimPage.setObjectName("btnAdjustPositionPrimPage")
        self.btnAdjustIdPrimPage = QtWidgets.QPushButton(Dialog)
        self.btnAdjustIdPrimPage.setGeometry(QtCore.QRect(390, 460, 241, 31))
        self.btnAdjustIdPrimPage.setObjectName("btnAdjustIdPrimPage")
        self.lnPrimPrimPage = QtWidgets.QLineEdit(Dialog)
        self.lnPrimPrimPage.setGeometry(QtCore.QRect(250, 290, 181, 31))
        self.lnPrimPrimPage.setObjectName("lnPrimPrimPage")
        self.lwShowPositionPrimPage = QtWidgets.QListWidget(Dialog)
        self.lwShowPositionPrimPage.setGeometry(QtCore.QRect(70, 510, 241, 231))
        self.lwShowPositionPrimPage.setObjectName("lwShowPositionPrimPage")
        self.lwShowIdPrimPage = QtWidgets.QListWidget(Dialog)
        self.lwShowIdPrimPage.setGeometry(QtCore.QRect(390, 510, 241, 231))
        self.lwShowIdPrimPage.setObjectName("lwShowIdPrimPage")
        self.btnShowPositionPrimPage = QtWidgets.QPushButton(Dialog)
        self.btnShowPositionPrimPage.setGeometry(QtCore.QRect(70, 760, 241, 31))
        self.btnShowPositionPrimPage.setObjectName("btnShowPositionPrimPage")
        self.btnShowIdPrimPage = QtWidgets.QPushButton(Dialog)
        self.btnShowIdPrimPage.setGeometry(QtCore.QRect(390, 760, 241, 31))
        self.btnShowIdPrimPage.setObjectName("btnShowIdPrimPage")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "By position "))
        self.label_2.setText(_translate("Dialog", "By Identity"))
        self.btnAdjustPositionPrimPage.setText(_translate("Dialog", "Adjust"))
        self.btnAdjustIdPrimPage.setText(_translate("Dialog", "Adjust"))
        self.lnPrimPrimPage.setPlaceholderText(_translate("Dialog", "Enter prim percentage"))
        self.btnShowPositionPrimPage.setText(_translate("Dialog", "Show New Salary"))
        self.btnShowIdPrimPage.setText(_translate("Dialog", "Show New Salary"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
