# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'salaries.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1081, 832)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 20, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.cmbPositionSalariesPage = QtWidgets.QComboBox(Dialog)
        self.cmbPositionSalariesPage.setGeometry(QtCore.QRect(190, 70, 271, 31))
        self.cmbPositionSalariesPage.setObjectName("cmbPositionSalariesPage")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lnIdSalariesPage = QtWidgets.QLineEdit(Dialog)
        self.lnIdSalariesPage.setGeometry(QtCore.QRect(190, 120, 271, 31))
        self.lnIdSalariesPage.setObjectName("lnIdSalariesPage")
        self.lwMainShowSalariesPage = QtWidgets.QListWidget(Dialog)
        self.lwMainShowSalariesPage.setGeometry(QtCore.QRect(20, 210, 441, 561))
        self.lwMainShowSalariesPage.setObjectName("lwMainShowSalariesPage")
        self.btnShowSalariesPage = QtWidgets.QPushButton(Dialog)
        self.btnShowSalariesPage.setGeometry(QtCore.QRect(190, 170, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnShowSalariesPage.setFont(font)
        self.btnShowSalariesPage.setObjectName("btnShowSalariesPage")
        self.chkMostPaidSalariesPage = QtWidgets.QCheckBox(Dialog)
        self.chkMostPaidSalariesPage.setGeometry(QtCore.QRect(620, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chkMostPaidSalariesPage.setFont(font)
        self.chkMostPaidSalariesPage.setObjectName("chkMostPaidSalariesPage")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(620, 240, 401, 192))
        self.listWidget_2.setObjectName("listWidget_2")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(620, 460, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.listWidget_3 = QtWidgets.QListWidget(Dialog)
        self.listWidget_3.setGeometry(QtCore.QRect(620, 540, 401, 281))
        self.listWidget_3.setObjectName("listWidget_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(700, 500, 121, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(620, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnUpdateSalariesPage = QtWidgets.QPushButton(Dialog)
        self.btnUpdateSalariesPage.setGeometry(QtCore.QRect(20, 780, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnUpdateSalariesPage.setFont(font)
        self.btnUpdateSalariesPage.setObjectName("btnUpdateSalariesPage")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Salaries"))
        self.label.setText(_translate("Dialog", "Employee Salary List"))
        self.label_2.setText(_translate("Dialog", "Position"))
        self.label_3.setText(_translate("Dialog", "Search by Id"))
        self.btnShowSalariesPage.setText(_translate("Dialog", "Show "))
        self.chkMostPaidSalariesPage.setText(_translate("Dialog", "The most paids"))
        self.checkBox_2.setText(_translate("Dialog", "The early employees"))
        self.label_4.setText(_translate("Dialog", "Number"))
        self.btnUpdateSalariesPage.setText(_translate("Dialog", "Update Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
