# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchById.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchById(object):
    def setupUi(self, SearchById):
        SearchById.setObjectName("SearchById")
        SearchById.resize(392, 159)
        self.label = QtWidgets.QLabel(SearchById)
        self.label.setGeometry(QtCore.QRect(20, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(SearchById)
        self.lineEdit.setGeometry(QtCore.QRect(100, 44, 261, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(SearchById)
        self.pushButton.setGeometry(QtCore.QRect(100, 100, 111, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/validate.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(SearchById)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 100, 111, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icons/cance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(SearchById)
        QtCore.QMetaObject.connectSlotsByName(SearchById)

        self.pushButton.clicked.connect(SearchById.close)
        self.pushButton_2.clicked.connect(self.cancel)
        self.pushButton_2.clicked.connect(SearchById.close)


    def cancel(self):
        self.lineEdit.setText("0")

    def retranslateUi(self, SearchById):
        _translate = QtCore.QCoreApplication.translate
        SearchById.setWindowTitle(_translate("SearchById", "Dialog"))
        self.label.setText(_translate("SearchById", "Identity"))
        self.lineEdit.setPlaceholderText(_translate("SearchById", "E.g: 99002"))
        self.pushButton.setText(_translate("SearchById", "Validate"))
        self.pushButton_2.setText(_translate("SearchById", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearchById = QtWidgets.QDialog()
    ui = Ui_SearchById()
    ui.setupUi(SearchById)
    SearchById.show()
    sys.exit(app.exec_())
