# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchNM.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchByName(object):
    def setupUi(self, searchByName):
        searchByName.setObjectName("searchByName")
        searchByName.resize(442, 161)
        self.label = QtWidgets.QLabel(searchByName)
        self.label.setGeometry(QtCore.QRect(10, 40, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(searchByName)
        self.lineEdit.setGeometry(QtCore.QRect(120, 34, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(searchByName)
        self.pushButton.setGeometry(QtCore.QRect(120, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/validate.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(searchByName)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icons/cance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(searchByName)
        QtCore.QMetaObject.connectSlotsByName(searchByName)

        self.pushButton.clicked.connect(searchByName.close)
        self.pushButton_2.clicked.connect(searchByName.close)

    def retranslateUi(self, searchByName):
        _translate = QtCore.QCoreApplication.translate
        searchByName.setWindowTitle(_translate("searchByName", "Dialog"))
        self.label.setText(_translate("searchByName", "Full Name"))
        self.lineEdit.setPlaceholderText(_translate("searchByName", "Tatiana Gagarina"))
        self.pushButton.setText(_translate("searchByName", "Validate"))
        self.pushButton_2.setText(_translate("searchByName", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    searchByName = QtWidgets.QDialog()
    ui = Ui_searchByName()
    ui.setupUi(searchByName)
    searchByName.show()
    sys.exit(app.exec_())
