# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Time(object):
    def setupUi(self, Time):
        Time.setObjectName("Time")
        Time.resize(569, 241)
        self.label = QtWidgets.QLabel(Time)
        self.label.setGeometry(QtCore.QRect(40, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Time)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Time)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lnActivityTime = QtWidgets.QLineEdit(Time)
        self.lnActivityTime.setGeometry(QtCore.QRect(220, 30, 301, 25))
        self.lnActivityTime.setObjectName("lnActivityTime")
        self.dateEditTime = QtWidgets.QDateEdit(Time)
        self.dateEditTime.setGeometry(QtCore.QRect(220, 80, 301, 26))
        self.dateEditTime.setObjectName("dateEditTime")
        self.timeEditStartTime = QtWidgets.QTimeEdit(Time)
        self.timeEditStartTime.setGeometry(QtCore.QRect(220, 130, 141, 26))
        self.timeEditStartTime.setObjectName("timeEditStartTime")
        self.timeEditFinishTime = QtWidgets.QTimeEdit(Time)
        self.timeEditFinishTime.setGeometry(QtCore.QRect(377, 130, 141, 26))
        self.timeEditFinishTime.setObjectName("timeEditFinishTime")
        self.btnValidateTime = QtWidgets.QPushButton(Time)
        self.btnValidateTime.setGeometry(QtCore.QRect(220, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnValidateTime.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/validate.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnValidateTime.setIcon(icon)
        self.btnValidateTime.setIconSize(QtCore.QSize(20, 20))
        self.btnValidateTime.setObjectName("btnValidateTime")

        self.btnCancelTime = QtWidgets.QPushButton(Time)
        self.btnCancelTime.setGeometry(QtCore.QRect(370, 180, 151, 31))

        self.btnValidateTime.clicked.connect(Time.close)

        self.btnCancelTime.clicked.connect(self.cancel)
        self.btnCancelTime.clicked.connect(Time.close)

        font = QtGui.QFont()
        font.setPointSize(13)
        self.btnCancelTime.setFont(font)
        icon = QtGui.QIcon.fromTheme("cancel")
        self.btnCancelTime.setIcon(icon)
        self.btnCancelTime.setIconSize(QtCore.QSize(20, 20))
        self.btnCancelTime.setObjectName("btnCancelTime")

        self.retranslateUi(Time)
        QtCore.QMetaObject.connectSlotsByName(Time)

    def cancel(self):
        self.lnActivityTime.setText("")

    def retranslateUi(self, Time):
        _translate = QtCore.QCoreApplication.translate
        Time.setWindowTitle(_translate("Time", "Dialog"))
        self.label.setText(_translate("Time", "Activity"))
        self.label_2.setText(_translate("Time", "Date"))
        self.label_3.setText(_translate("Time", "Start & Finish Time"))
        self.btnValidateTime.setText(_translate("Time", "Validate"))
        self.btnCancelTime.setText(_translate("Time", "Cancel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Time = QtWidgets.QDialog()
    ui = Ui_Time()
    ui.setupUi(Time)
    Time.show()
    sys.exit(app.exec_())
